//login

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

// get latest user
export const GET_ALL_USER_REQUEST = 'GET_ALL_USER_REQUEST'
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const GET_ALL_USER_FAILED = 'GET_ALL_USER_FAILED'

// get all tasks
export const GET_ALL_TASK_REQUEST = 'GET_ALL_TASK_REQUEST'
export const GET_ALL_TASK_SUCCESS = 'GET_ALL_TASK_SUCCESS'
export const GET_ALL_TASK_FAILED = 'GET_ALL_TASK_FAILED'

// get all members
export const GET_ALL_MEMBER_REQUEST = 'GET_ALL_MEMBER_REQUEST'
export const GET_ALL_MEMBER_SUCCESS = 'GET_ALL_MEMBER_SUCCESS'
export const GET_ALL_MEMBER_FAILED = 'GET_ALL_MEMBER_FAILED'

// new task
export const ADD_NEW_TASK_REQUEST = 'ADD_NEW_TASK_REQUEST'
export const ADD_NEW_TASK_SUCCESS = 'ADD_NEW_TASK_SUCCESS'
export const ADD_NEW_TASK_FAILED = 'ADD_NEW_TASK_FAILED'

// new member
export const ADD_NEW_MEMBER_REQUEST = 'ADD_NEW_MEMBER_REQUEST'
export const ADD_NEW_MEMBER_SUCCESS = 'ADD_NEW_MEMBER_SUCCESS'
export const ADD_NEW_MEMBER_FAILED = 'ADD_NEW_MEMBER_FAILED'

// update member
export const UPDATE_MEMBER_REQUEST = 'UPDATE_MEMBER_REQUEST'
export const UPDATE_MEMBER_SUCCESS = 'UPDATE_MEMBER_SUCCESS'
export const UPDATE_MEMBER_FAILED = 'UPDATE_MEMBER_FAILED'

// update task
export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED'

// delete member
export const DELETE_MEMBER_REQUEST = 'DELETE_MEMBER_REQUEST'
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS'
export const DELETE_MEMBER_FAILED = 'DELETE_MEMBER_FAILED'

// delete task
export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED'